version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-fordocker
  app:
    build:
      context: .
    env_file:
      - .env-fordocker
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "7432:8000"
    depends_on:
      - db