"""User_Responses table

Revision ID: 1c9369112dc4
Revises: d39d93850674
Create Date: 2024-05-12 00:19:58.204121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9369112dc4'
down_revision: Union[str, None] = 'd39d93850674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('resp_date', sa.DateTime(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_form_id'), 'response', ['form_id'], unique=False)
    op.create_index(op.f('ix_response_resp_date'), 'response', ['resp_date'], unique=False)
    op.create_index(op.f('ix_response_user_id'), 'response', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_user_id'), table_name='response')
    op.drop_index(op.f('ix_response_resp_date'), table_name='response')
    op.drop_index(op.f('ix_response_form_id'), table_name='response')
    op.drop_table('response')
    # ### end Alembic commands ###
